### ISSUE TITLE
Tokenizer for facebook/musicgen-small 

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [openvinotoolkit/openvino_tokenizers#37]
Hello, I am trying to convert a tokenizer for use with ```facebook/musicgen-small```. This is the model used in this notebook:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/250-music-generation/250-music-generation.ipynb

But it is failing with the following:
```
> convert_tokenizer facebook/musicgen-small --with-detokenizer -o musicgen-small-tokenizer
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading Huggingface Tokenizer...
Converting Huggingface Tokenizer to OpenVINO...
sentence_piece.cpp(88) [_status.ok()] Internal: C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019@2\b\tmp\tmpwymvb8fg\build\_deps\sentencepiece-src\src\sentencepiece_processor.cc(1055) [!IsUnknown(PieceToId(absl::string_view(model_->bos_piece().data())))] id for `<s>` is not defined.
Program terminated with an unrecoverable error.
```

Any ideas?

Thanks!

**Comment by apaniukov** [comment]
Hi Ryan,
Yes, there is a bug that causes this issue. I created [a PR](https://github.com/openvinotoolkit/openvino_tokenizers/pull/39) with a fix. It will be added to the next version - 2024.0.0.0.

If you want to access the fix now, there are a couple of options:
1. [Install openvino-tokenizers](https://github.com/openvinotoolkit/openvino_tokenizers#build-and-install-from-source-after-openvino-installation) from the fork branch of the git repository (or from the master after PR will be merged). It requires OpenVINO Archive distribution to build tokenizers binaries.
1. Add [changes](https://github.com/openvinotoolkit/openvino_tokenizers/pull/39/files#diff-7daa0a46d666790e3a6eb6bacb7b50bcf86ddc41d44d113cd9689374e36b6669) to the python code in the installed openvino-tokenizers library.

The second option is easier. To locate the file you can use this code:
```python
from openvino_tokenizers import hf_parser
print(hf_parser.__file__)
```

After getting the tokenizer model with the modified library, it will work with any openvino-tokenizers version, since the bug is in the conversion stage.

**Comment by apaniukov** [comment]
> So, I added this (which I guess is the only dll that would make sense here):
```core.add_extension("core_tokenizers.dll");```

Yes, I can see how it can be misleading. The dll you need is `user_ov_extension.dll`, which is already renamed to `openvino_tokenizers.dll` on master branch. Basically:
- `user_ov_extension.dll` for 2023.0.0.0 version
- `openvino_tokenizers.dll` for any future (or builded locally) versions

**Comment by RyanMetcalfeInt8** [comment]
Hi @apaniukov,

Ah, got it -- thank you! I didn't even notice that ```user_ov_extensions.dll``` was one of the DLL's included. Yes that seems to work.

By the way, will these eventually get included into OpenVINO itself in a future release (like 2024.X)?

**Comment by andrei-kochin** [comment]
Hello @RyanMetcalfeInt8,

At least for all upcoming 24.x releases the plan is to have all tokenizers in the separate package and maybe later on if it would be required they would become a part of the OpenVINO opset.

Best regards,
Andrei

**Comment by RyanMetcalfeInt8** [comment]
Hi @andrei-kochin -- makes sense. Thanks!
